package mx.gob.imss.dpes.common.enums;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.HashMap;
import java.util.Map;
import lombok.Getter;

/**
 *
 * @author antonio
 */
public enum BitacoraEnum {
  GENERAR_INFORME_CAPACIDAD(1L)
  ,GENERAR_CARTA_CAPACIDAD_CREDITO(2L)
  ,INGRESA_MONTO_SOLICITADO_POR_MONTO(3L)
  ,SELECCIONA_PLAZO(4L)
  ,SELECCIONA_PROPUESTA_SIMULACION(5L)
  ,GENERAR_RESUMEN_SIMULACION(6L)
  ,SIMULACION_INICIADA(7L)
  ,SIMULAR_POR_MONTO_PRESTAMO_VIGENTE(8L)    
  ,INGRESA_MONTO_SOLICITADO_POR_DESCUENTO(9L)
  ,GENERAR_CARTA_INSTRUCCION(10L)
  ,TERMINOS_CONDICIONES_NO_ACEPTADAS(11L)
  ,DESCUENTO_MENSUAL_MAYOR_CAPACIDAD_FIJA(12L)
  ,DESCUENTO_MENSUAL_MAYOR_CAPACIDAD_TOTAL(13L)
  ,CAT_INCORRECTO(14L)
  ,GENERACION_CARTA_NO_ACEPTADA(15L)
  ,BUSCAR_FOLIO_ESTADO_PENDIENTE_MONTO_LIQUIDAR(16L)
  ,BUSCAR_FOLIO_ESTADO_DIFERENTE_INICIADO(17L)
  ,ANEXAR_COMPROBANTE(18L)
  ,AUTORIZAR_PRESTAMO(19L)
  ,AUTORIZACION_NO_CONFIRMADA(20L)
  ,CANCELACION_NO_CONFIRMADA(21L)
  ,CANCELAR_FOLIO_NEGOCIO(23L)
  ,CONSULTA_DATOS_PENSIONADO(24L)
  ,CONFIRMA_MONTO_LIQUIDAR(25L)
  ,CANCELAR_ACTUALIZACION_DATOS_CONTACTO(26L)
  ,CANCELAR_PRESTAMO(27L)
  ,SUSPENDER_PRESTAMO(28L)
  ,REANUDAR_PRESTAMO(29L)
  ,CARGA_CEP_CANCELADA(30L)
  ,ACTUALIZACION_NOMBRE_PENSIONADO(31L)
  ,BAJA_OPERADOR_EF(32L)
  ,SUSPENSION_OPERADOR_EF(33L)
  ,REACTIVACION_OPERADOR_EF(34L)
  ,REGISTRO_OPERADOR_EF(35L)
  ,ACTUALIZACION_CAT_MAXIMO(36L)
  ,NUEVO_CAT_EF(37L)
  ,ACTUALIZACION_CAT_EF(38L)
  ,BAJA_CAT_EF(39L)
  ,GENERACION_CARTA_REINSTALACION(43L)
  ,CANCELACION_AUTOMATICA(44L)
  ,CONFIRMACION_AUTOMATICA_MONTO_LIQUIDAR(45L)
  ;
  
  private BitacoraEnum(Long id) {
    this.id = id;
  }
  
  @Getter Long id;
  
  private static final Map<Long, BitacoraEnum> map = new HashMap<>();
  
  static{
    map.put(GENERAR_INFORME_CAPACIDAD.id,GENERAR_INFORME_CAPACIDAD);
    map.put(GENERAR_CARTA_CAPACIDAD_CREDITO.id,  GENERAR_CARTA_CAPACIDAD_CREDITO);
    map.put(INGRESA_MONTO_SOLICITADO_POR_MONTO.id,  INGRESA_MONTO_SOLICITADO_POR_MONTO);
    map.put(SELECCIONA_PLAZO.id,  SELECCIONA_PLAZO);
    map.put(SELECCIONA_PROPUESTA_SIMULACION.id,  SELECCIONA_PROPUESTA_SIMULACION);
    map.put(GENERAR_RESUMEN_SIMULACION.id,  GENERAR_RESUMEN_SIMULACION);
    map.put(SIMULACION_INICIADA.id,  SIMULACION_INICIADA);
    map.put(SIMULAR_POR_MONTO_PRESTAMO_VIGENTE.id,  SIMULAR_POR_MONTO_PRESTAMO_VIGENTE);
    map.put(INGRESA_MONTO_SOLICITADO_POR_DESCUENTO.id,  INGRESA_MONTO_SOLICITADO_POR_DESCUENTO);
    map.put(GENERAR_CARTA_INSTRUCCION.id,  GENERAR_CARTA_INSTRUCCION);
    map.put(TERMINOS_CONDICIONES_NO_ACEPTADAS.id,  TERMINOS_CONDICIONES_NO_ACEPTADAS);
    map.put(DESCUENTO_MENSUAL_MAYOR_CAPACIDAD_FIJA.id,  DESCUENTO_MENSUAL_MAYOR_CAPACIDAD_FIJA);
    map.put(DESCUENTO_MENSUAL_MAYOR_CAPACIDAD_TOTAL.id,  DESCUENTO_MENSUAL_MAYOR_CAPACIDAD_TOTAL);
    map.put(CAT_INCORRECTO.id,  CAT_INCORRECTO);
    map.put(GENERACION_CARTA_NO_ACEPTADA.id,  GENERACION_CARTA_NO_ACEPTADA);
    map.put(BUSCAR_FOLIO_ESTADO_PENDIENTE_MONTO_LIQUIDAR.id,  BUSCAR_FOLIO_ESTADO_PENDIENTE_MONTO_LIQUIDAR);
    map.put(BUSCAR_FOLIO_ESTADO_DIFERENTE_INICIADO.id,  BUSCAR_FOLIO_ESTADO_DIFERENTE_INICIADO);
    map.put(ANEXAR_COMPROBANTE.id,  ANEXAR_COMPROBANTE);
    map.put(AUTORIZAR_PRESTAMO.id,  AUTORIZAR_PRESTAMO);
    map.put(AUTORIZACION_NO_CONFIRMADA.id,  AUTORIZACION_NO_CONFIRMADA);
    map.put(CANCELACION_NO_CONFIRMADA.id,  CANCELACION_NO_CONFIRMADA);
    map.put(CANCELAR_FOLIO_NEGOCIO.id,  CANCELAR_FOLIO_NEGOCIO);
    map.put(CONSULTA_DATOS_PENSIONADO.id,  CONSULTA_DATOS_PENSIONADO);
    map.put(CONFIRMA_MONTO_LIQUIDAR.id, CONFIRMA_MONTO_LIQUIDAR);
    map.put(CANCELAR_ACTUALIZACION_DATOS_CONTACTO.id, CANCELAR_ACTUALIZACION_DATOS_CONTACTO );
    map.put(CANCELAR_PRESTAMO.id, CANCELAR_PRESTAMO);
    map.put(SUSPENDER_PRESTAMO.id, SUSPENDER_PRESTAMO);
    map.put(REANUDAR_PRESTAMO.id, REANUDAR_PRESTAMO);
    map.put(CARGA_CEP_CANCELADA.id, CARGA_CEP_CANCELADA);
    map.put(ACTUALIZACION_NOMBRE_PENSIONADO.id, ACTUALIZACION_NOMBRE_PENSIONADO);
    map.put(BAJA_OPERADOR_EF.id, BAJA_OPERADOR_EF);
    map.put(SUSPENSION_OPERADOR_EF.id, SUSPENSION_OPERADOR_EF);
    map.put(REACTIVACION_OPERADOR_EF.id, REACTIVACION_OPERADOR_EF);
    map.put(REGISTRO_OPERADOR_EF.id, REGISTRO_OPERADOR_EF);
    map.put(ACTUALIZACION_CAT_MAXIMO.id, ACTUALIZACION_CAT_MAXIMO);
    map.put(NUEVO_CAT_EF.id, NUEVO_CAT_EF);
    map.put(ACTUALIZACION_CAT_EF.id, ACTUALIZACION_CAT_EF);
    map.put(BAJA_CAT_EF.id, BAJA_CAT_EF);
    map.put(GENERACION_CARTA_REINSTALACION.id, GENERACION_CARTA_REINSTALACION);
    map.put(CANCELACION_AUTOMATICA.id, CANCELACION_AUTOMATICA);
    map.put(CONFIRMACION_AUTOMATICA_MONTO_LIQUIDAR.id, CONFIRMACION_AUTOMATICA_MONTO_LIQUIDAR);
  }
  
  @JsonCreator
  public static BitacoraEnum forValue(Long value) {
      return map.get(value);
  }
  
  @JsonValue
  public Long toValue() {
    for (Map.Entry<Long, BitacoraEnum> entry : map.entrySet() ) {
      if (entry.getValue( ) == this )
        return entry.getKey();
    }
    return null;
  }
  
}
